//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bron
    {
        public int ID { get; set; }
        public int Client_ID { get; set; }
        public int Nomer_ID { get; set; }
        public System.DateTime Data_zaseleniya { get; set; }
        public System.DateTime Data_visilenia { get; set; }
    }
}
