//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConceptHotelEntities : DbContext
    {
        public ConceptHotelEntities()
            : base("name=ConceptHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bron> Bron { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Nomera> Nomera { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoomsType> RoomsType { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
