//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomera
    {
        public int ID { get; set; }
        public int Nomer { get; set; }
        public string Tip { get; set; }
        public string Phone { get; set; }
        public string Free { get; set; }
    }
}
